[unix_http_server]
file=/run/supervisor.sock
chmod=0770

[supervisord]
nodaemon=true
logfile=/dev/stdout
logfile_maxbytes=0
pidfile=/run/supervisord.pid

[rpcinterface:supervisor]
supervisor.rpcinterface_factory = supervisor.rpcinterface:make_main_rpcinterface

[supervisorctl]
serverurl=unix:///run/supervisor.sock

[program:octane]
command=php artisan octane:start --server=frankenphp --host=0.0.0.0 --port=8000 --workers=4
directory=/var/www/html
autostart=true
autorestart=true
startretries=5
numprocs=1
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0
