[supervisord]
nodaemon=true

[program:octane]
command=php artisan octane:start --host=0.0.0.0 --port=8000 --workers=4
autostart=false
autorestart=true
numprocs=1
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0
