prefix = /usr
localstatedir = /var
sbindir = /usr/sbin
logdir = /var/log/freeradius
raddbdir = /etc/raddb
radacctdir = /var/log/freeradius/radacct

confdir = ${raddbdir}
run_dir = ${localstatedir}/run/freeradius

pidfile = ${run_dir}/freeradius.pid

user = freerad
group = freerad

max_request_time = 30
cleanup_delay = 5
max_requests = 1024

listen {
    type = auth
    ipaddr = *
    port = 1812
}

listen {
    type = acct
    ipaddr = *
    port = 1813
}

listen {
    type = auth
    ipaddr = 127.0.0.1
    port = 18120
}

log {
    destination = files
    file = ${logdir}/radius.log
    syslog_facility = daemon
    stripped_names = no
    auth = yes
    auth_badpass = no
    auth_goodpass = no
    colourise = yes
}

checkrad = ${sbindir}/checkrad

security {
    max_attributes = 200
    reject_delay = 1
    status_server = yes
}

$INCLUDE  ${confdir}/clients.conf
$INCLUDE  ${confdir}/mods-enabled/
$INCLUDE  ${confdir}/sites-enabled/
